### PR TITLE
Update to latest flightgear release

### PR DESCRIPTION
**Pull request by popey**
There's a new release of flightgear. This updates the yaml to pull that new release.

### CODE REVIEW

**Comment by brlin-tw** [comment]
LGTM.

**Comment by popey** [comment]
I have tested this on Kubuntu 21.04. I believe it's ready to merge.
image

**Comment by brlin-tw** [comment]
@snapcrafters/reviewers Can anyone help on reviewing and merging this?

**Comment by merlijn-sebrechts** [comment]
LGTM

**Comment by merlijn-sebrechts** [comment]
Since I'm not a maintainer, I do not have access to the snap in the store. @Lin-Buo-Ren Maybe make a call for testing once the edge build finishes where you also ask the canonical people to merge this if testing succeeds?

**Comment by ghost** [comment]
What kind of testing is required please? I can do some, but I don't have any fancy equipment like controllers, joysticks.

**Pull request merged**
